version: 2
updates:
- package-ecosystem: gomod
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 20
- package-ecosystem: npm
  directory: "/lp"
  schedule:
    interval: daily
  open-pull-requests-limit: 20
- package-ecosystem: npm
  directory: "/assets"
  schedule:
    interval: daily
  open-pull-requests-limit: 20
