version: '2'
services:
  storage:
    image: busybox
    volumes:
      - /var/lib/mysql
  mysql:
    image: mysql:5.7
    volumes_from:
      - storage
    ports:
      - "3306:3306"
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "true"
  node:
    build: dockerfiles/development/node
    volumes:
      - .:/var/opt/app
    entrypoint: bash -c
    command: |
      "npm install && \
      npm run-script watch"
  go:
    image: h3poteto/golang
    env_file: .docker-env
    environment:
      GOJIROOT: /go/src/github.com/h3poteto/fascia
      GOJIENV: development
    volumes:
      - .:/go/src/github.com/h3poteto/fascia
    working_dir: /go/src/github.com/h3poteto/fascia
    links:
      - mysql:mysql
      - node:node
    ports:
      - "9090:9090"
    command: /bin/sh

