mysql:
  image: mysql
  volumes:
    - ~/docker-data/mysql:/var/lib/mysql
  ports:
    - "3307:3306"
  environment:
    MYSQL_ROOT_PASSWORD: mysql
node:
  image: node:5.9.1-slim
  volumes:
    - .:/var/opt
  working_dir: /var/opt
  command: npm run-script watch
fascia:
  build: .
  volumes:
    - .:/go/src/fascia
  links:
    - mysql:mysql
    - node:node
  ports:
    - "9090:9090"
  command: gom run server.go

