version: '3'
services:
  storage:
    image: busybox
    volumes:
      - /var/lib/mysql
  mysql:
    image: mysql:5.7
    volumes:
      - storage:/var/lib/mysql
    ports:
      - "3306:3306"
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "3"
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "true"
  node:
    image: node:7-alpine
    user: node
    volumes:
      - .:/var/opt/app
    working_dir: /var/opt/app
    entrypoint: sh -c
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "3"
    command: |
      "npm install && \
      npm run watch"
  go:
    image: h3poteto/golang:1.9.1
    env_file: .docker-env
    environment:
      APPROOT: /go/src/github.com/h3poteto/fascia
      APPENV: development
      AWS_DEFAULT_REGION: us-east-1
      AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
      AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
    volumes:
      - .:/go/src/github.com/h3poteto/fascia
    working_dir: /go/src/github.com/h3poteto/fascia
    links:
      - mysql:mysql
      - node:node
    ports:
      - "9090:9090"
    command: /bin/sh
volumes:
  storage:
