storage:
  build: dockerfiles/storage
mysql:
  image: mysql
  volumes_from:
    - storage
  ports:
    - "3307:3306"
  environment:
    MYSQL_ROOT_PASSWORD: mysql
node:
  build: dockerfiles/node
  volumes:
    - .:/var/opt/app
  command: npm run-script watch
fascia:
  build: dockerfiles/fascia
  volumes:
    - ~/.ssh:/root/.ssh
    - .:/go/src/fascia
  links:
    - mysql:mysql
    - node:node
  ports:
    - "9090:9090"
  command: gom run server.go

