version: '2'
services:
  storage:
    image: busybox
    volumes:
      - /var/lib/mysql
  mysql:
    image: mysql:5.6.29
    volumes_from:
      - storage
    ports:
      - "3307:3306"
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "true"
  node:
    build: dockerfiles/development/node
    volumes:
      - .:/var/opt/app
    command: npm install && npm run-script watch
  go:
    build: dockerfiles/development/fascia
    env_file: .docker-env
    volumes:
      - ~/.ssh:/root/.ssh
      - .:/go/src/github.com/h3poteto/fascia
    links:
      - mysql:mysql
      - node:node
    ports:
      - "9090:9090"
    command: /bin/sh

