version: '3'
services:
  storage:
    image: busybox
    volumes:
      - /var/lib/mysql
  mysql:
    image: mysql:5.7
    volumes:
      - storage:/var/lib/mysql
    ports:
      - "3306:3306"
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "3"
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "true"
  node:
    image: h3poteto/node:10.12.0-alpine
    volumes:
      - .:/var/opt/app
    working_dir: /var/opt/app
    entrypoint: sh -c
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "3"
    command: |
      "npm install && \
      npm run watch"
  go:
    image: h3poteto/golang:1.9.4
    environment:
      APPROOT: /go/src/github.com/h3poteto/fascia
      APPENV: development
      AWS_DEFAULT_REGION: us-east-1
      AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
      AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
      DATABASE_URL: mysql
      DB_USER: root
      DB_NAME: fascia
      DB_TEST_NAME: fascia_test
      CLIENT_ID: $CLIENT_ID
      CLIENT_SECRET: $CLIENT_SECRET
      SLACK_URL: $SLACK_URL
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_DB_NUMBER: 0
    volumes:
      - .:/go/src/github.com/h3poteto/fascia
    working_dir: /go/src/github.com/h3poteto/fascia
    links:
      - mysql:mysql
      - redis:redis
    ports:
      - "9090:9090"
    command: /bin/sh

  redis:
    image: redis:5.0-alpine

volumes:
  storage:
