[[constraint]]
  branch = "master"
  name = "github.com/flosch/pongo2"

[[constraint]]
  name = "github.com/ipfans/echo-session"
  version = "v3.1.1"

[[constraint]]
  name = "github.com/labstack/echo"
  version = "v3.2.1"
