
[[dependencies]]
  branch = "master"
  name = "github.com/flosch/pongo2"

[[dependencies]]
  name = "github.com/ipfans/echo-session"
  version = "v3.0.0-rc1"

[[dependencies]]
  branch = "master"
  name = "github.com/labstack/echo"
