version: '3'
services:
  go:
    image: h3poteto/fascia
    environment:
      DATABASE_URL: $DATABASE_URL
      DB_USER: $DB_USER
      DB_NAME: $DB_NAME
      DB_PASSWORD: $DB_PASSWORD
      CLIENT_ID: $CLIENT_ID
      CLIENT_SECRET: $CLIENT_SECRET
      SLACK_URL: $SLACK_URL
    healthcheck:
      test: ["CMD", "curl", "-f", "http://127.0.0.1:9090"]
      interval: 20s
      timeout: 10s
      retries: 3
    deploy:
      replicas: 2
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 5
        window: 120s
      update_config:
        parallelism: 1
        delay: 20s
    stop_grace_period: 20s
  nginx:
    image: nginx:1.13-alpine
    depends_on:
      - go
    ports:
      - "80:80"
      - "443:443"
    environment:
      SERVER_ADDR: go
      SERVER_PORT: 9090
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf.template:ro
      - /var/log/nginx/:/var/log/nginx/
    command: /bin/sh -c "envsubst '$$SERVER_ADDR$$SERVER_PORT' < /etc/nginx/conf.d/default.conf.template > /etc/nginx/nginx.conf && nginx -g 'daemon off;'"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost"]
      interval: 20s
      timeout: 10s
      retries: 3
    deploy:
      replicas: 2
      update_config:
        parallelism: 1
        delay: 20s
    stop_grace_period: 10s
