development:
  init_list:
    todo: "ToDo"
    inprogress: "InProgress"
    done: "Done"
    none: "None"
  session:
    timeout: 3600
  mail:
    from: "fascia.server+dev@gmail.com"
    to: "fascia.server+dev@gmail.com"
test:
  init_list:
    todo: "ToDo"
    inprogress: "InProgress"
    done: "Done"
    none: "None"
  session:
    timeout: 3600
  mail:
    from: "fascia.server+test@gmail.com"
    to: "fascia.server+test@gmail.com"
production:
  init_list:
    todo: "ToDo"
    inprogress: "InProgress"
    done: "Done"
    none: "None"
  session:
    timeout: 604800 # 1week
  mail:
    from: "no-reply@fascia.io"
    to: "info@fascia.io"