development:
  init_list:
    todo: "ToDo"
    inprogress: "InProgress"
    done: "Done"
    none: "None"
  session:
    timeout: 3600
  mail:
    from: "fascia.server+dev@gmail.com"
    to: "fascia.server+dev@gmail.com"
  fqdn: "fascia.localdomain"
  protocol: "http"
test:
  init_list:
    todo: "ToDo"
    inprogress: "InProgress"
    done: "Done"
    none: "None"
  session:
    timeout: 3600
  mail:
    from: "fascia.server+test@gmail.com"
    to: "fascia.server+test@gmail.com"
  fqdn: "localhost"
  protocol: "http"
production:
  init_list:
    todo: "ToDo"
    inprogress: "InProgress"
    done: "Done"
    none: "None"
  session:
    timeout: 604800 # 1week
  mail:
    from: "support@fascia.io"
    to: "support@fascia.io"
  fqdn: "fascia.io"
  protocol: "https"
