name: Go

on:
  pull_request:

jobs:

  build:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:13.5-alpine
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: master
          POSTGRES_PASSWORD: docker
          POSTGRES_DB: fascia_test

    container:
      image: ghcr.io/h3poteto/golang:1.16.10
      env:
        APPROOT: /go/src/github.com/h3poteto/fascia
        APPENV: test
        POSTGRES_HOST: postgres
        POSTGRES_DB: fascia_test
        POSTGRES_USER: master
        POSTGRES_PASSWORD: docker


    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16

    - uses: actions/cache@v2
      with:
        path: |
          ~/.cache/go-build
          /go/pkg/mod
        key: ${{ runner.os }}-go1.16-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go1.16-

    - name: Install
      run: go mod download
    - name: Build
      run: go build -v ./...
    - name: Migrate database
      run: goose -env test up
    - name: Test
      run: gingko -r ./
