name: reviewdog

on:
  pull_request:

jobs:
  golangci-lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-go@v2
        with:
          go-version: '^1.16.0'
      - uses: reviewdog/action-setup@v1
      - name: Install golangci-lint
        run: |
          curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.47.2
          golangci-lint --version
      - name: Run golangci-lint
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ github.token }}
        run: |
          golangci-lint run --timeout 3m | reviewdog -f=golangci-lint -reporter=github-pr-review -filter-mode=diff_context -fail-on-error=true

  eslint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install
        working-directory: ./assets
        run: |
          npm install
      - uses: reviewdog/action-setup@v1
      - name: Run eslint
        working-directory: ./assets
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ github.token }}
        run: |
          npm run lint | reviewdog -f=eslint -reporter=github-pr-review -filter-mode=diff_context -fail-on-error=true
